/**
 * The AI-image gate. Every coin image goes through up to three detectors:
 *
 *  1. provenance  – always on. Reads the file's own metadata: C2PA / IPTC
 *                   "trainedAlgorithmicMedia" tags, generator signatures
 *                   (Stable Diffusion "parameters", ComfyUI workflows,
 *                   Midjourney / DALL·E / Firefly / Imagen credits).
 *                   Precise when present, easy to strip, so never the only check.
 *  2. sightengine – optional. A dedicated AI-generated-image classifier.
 *  3. claude      – optional. Claude looks at the picture and judges it.
 *
 * The launch is blocked when any detector puts the probability that the
 * image is AI-generated at or above AI_BLOCK_THRESHOLD. A detector that is
 * configured but fails makes the whole check fail (the gate fails closed).
 */
import { createHash } from "node:crypto";
import Anthropic from "@anthropic-ai/sdk";
import { betaZodOutputFormat } from "@anthropic-ai/sdk/helpers/beta/zod";
import * as z from "zod/v4";
import { serverConfig } from "./config";
import { signToken, verifyToken } from "./tokens";

export type Verdict = "ai" | "human" | "unclear";
export type DetectorName = "provenance" | "sightengine" | "claude";

export interface Signal {
  source: DetectorName;
  /** 0 = certainly human-made, 1 = certainly AI-generated. */
  aiProbability: number;
  summary: string;
  details: string[];
}

export interface ImageVerdict {
  allowed: boolean;
  verdict: Verdict;
  aiProbability: number;
  threshold: number;
  detectors: DetectorName[];
  signals: Signal[];
  /** One line for the UI. */
  summary: string;
  /** sha256 of the image bytes. */
  hash: string;
}

export const sightengineConfigured = () => !!(serverConfig.sightengineUser && serverConfig.sightengineSecret);
export const claudeConfigured = () => !!serverConfig.anthropicApiKey;

export function detectorNames(): DetectorName[] {
  const d: DetectorName[] = ["provenance"];
  if (sightengineConfigured()) d.push("sightengine");
  if (claudeConfigured()) d.push("claude");
  return d;
}

/** Launches are allowed only when a real detector backs the metadata check (or the operator opted out). */
export const gateReady = () => detectorNames().length > 1 || serverConfig.allowMetadataOnlyGate;

export const imageHash = (bytes: Uint8Array) => createHash("sha256").update(bytes).digest("hex");

/* ------------------------------------------------------------------ provenance */

const STRONG: [RegExp, string][] = [
  [/trainedAlgorithmicMedia/i, "IPTC digital source type says the picture was created by a trained algorithm"],
  [/Steps: \d+, Sampler: /, "Stable Diffusion generation parameters are embedded in the file"],
  [/"class_type"\s*:\s*"[^"]*(KSampler|CLIPTextEncode)/, "A ComfyUI workflow is embedded in the file"],
  [/stable[ \-_]?diffusion/i, "Credited to Stable Diffusion"],
  [/midjourney/i, "Credited to Midjourney"],
  [/dall[·\-.]?e/i, "Credited to DALL·E"],
  [/comfyui/i, "Credited to ComfyUI"],
  [/novelai/i, "Credited to NovelAI"],
  [/adobe firefly/i, "Credited to Adobe Firefly"],
  [/google imagen|imagen[ \-]?\d/i, "Credited to Google Imagen"],
  [/ideogram/i, "Credited to Ideogram"],
  [/leonardo[ .]?ai/i, "Credited to Leonardo.Ai"],
  [/bing image creator|microsoft designer/i, "Credited to Bing Image Creator"],
  [/automatic1111|sd-webui|invokeai|fooocus|forge webui/i, "Made with a Stable Diffusion web UI"],
  [/flux[.\-_ ]?1|black[ -]forest[ -]labs/i, "Credited to FLUX"],
  [/krea\.ai|recraft\.ai|runwayml|nano[ -]banana|gpt-image|chatgpt|openai|grok imagine/i, "Credited to an AI image generator"],
  [/ai[ -]generated|generated by ai|\baigc\b/i, "The metadata labels the image as AI-generated"],
];

function provenance(bytes: Uint8Array): Signal {
  const text = Buffer.from(bytes).toString("latin1");
  const details: string[] = [];
  for (const [re, why] of STRONG) if (re.test(text)) details.push(why);
  const credentials = /urn:c2pa|c2pa\.|jumbf/i.test(text);
  if (details.length) {
    return { source: "provenance", aiProbability: 0.98, summary: "The file's own metadata says it was AI-generated.", details };
  }
  if (credentials) {
    return {
      source: "provenance",
      aiProbability: 0.25,
      summary: "The file carries Content Credentials without an AI-generation claim.",
      details: ["C2PA manifest present, no AI assertion found"],
    };
  }
  return { source: "provenance", aiProbability: 0.1, summary: "No AI generator signature in the file metadata.", details: [] };
}

/* ----------------------------------------------------------------- sightengine */

async function sightengine(bytes: Uint8Array, mime: string): Promise<Signal> {
  const form = new FormData();
  form.append("media", new Blob([Buffer.from(bytes)], { type: mime }), "image");
  form.append("models", "genai");
  form.append("api_user", serverConfig.sightengineUser);
  form.append("api_secret", serverConfig.sightengineSecret);
  const res = await fetch("https://api.sightengine.com/1.0/check.json", { method: "POST", body: form });
  const json = (await res.json().catch(() => ({}))) as { status?: string; type?: { ai_generated?: number }; error?: { message?: string } };
  if (!res.ok || json.status !== "success" || typeof json.type?.ai_generated !== "number") {
    throw new Error(`Sightengine check failed: ${json.error?.message ?? res.status}`);
  }
  const p = json.type.ai_generated;
  return {
    source: "sightengine",
    aiProbability: p,
    summary: `Sightengine rates it ${Math.round(p * 100)}% likely AI-generated.`,
    details: [],
  };
}

/* ---------------------------------------------------------------------- claude */

const Assessment = z.object({
  verdict: z.enum(["ai_generated", "human_made", "unclear"]),
  /** How sure the model is of the verdict, 0–1. */
  confidence: z.number().min(0).max(1),
  reasons: z.array(z.string()).max(6),
});

const SYSTEM = `You are an image forensics analyst for a token launchpad that only accepts human-made artwork and photographs.

Decide whether the image was produced by a generative AI model: text-to-image, image-to-image, or AI inpainting/outpainting that makes up most of the picture.

Human-made includes photographs, hand-drawn or digitally painted art, 3D renders built by a person, memes and screenshots assembled by hand, logos, pixel art and typographic designs. Light AI touch-ups (background removal, upscaling, filters) do not make an image AI-generated.

Evidence that points to AI generation: malformed hands, teeth, eyes or ears; melted or nonsensical text and logos; impossible geometry; inconsistent lighting, shadows or reflections; airbrushed skin and textures with hyper-detail elsewhere; the characteristic look of Midjourney, DALL·E, Stable Diffusion, FLUX, Imagen or similar models; AI watermarks such as the DALL·E colour bar in a corner.

Weigh the evidence and answer "unclear" when the image is too small or too simple (flat icons, plain text, solid shapes) to tell, or when it is genuinely ambiguous. Report confidence as your probability that the verdict is right, and give short concrete reasons that a user can understand.`;

let anthropic: Anthropic | null = null;

async function claude(bytes: Uint8Array, mime: string): Promise<Signal> {
  if (!anthropic) anthropic = new Anthropic({ apiKey: serverConfig.anthropicApiKey, timeout: 90_000, maxRetries: 2 });
  const media_type = mime as "image/png" | "image/jpeg" | "image/gif" | "image/webp";
  const response = await anthropic.beta.messages.parse({
    model: "claude-opus-5-5",
    max_tokens: 8000,
    // On a policy decline the API re-runs the request on a fallback model inside the same call.
    betas: ["server-side-fallback-2026-07-01"],
    fallbacks: "default",
    system: SYSTEM,
    output_config: { effort: "high", format: betaZodOutputFormat(Assessment) },
    messages: [
      {
        role: "user",
        content: [
          { type: "image", source: { type: "base64", media_type, data: Buffer.from(bytes).toString("base64") } },
          { type: "text", text: "Assess whether this coin image is AI-generated." },
        ],
      },
    ],
  });
  if (response.stop_reason === "refusal" || !response.parsed_output) {
    throw new Error("Claude could not assess this image. Try a different image.");
  }
  const a = response.parsed_output;
  // Map verdict + confidence onto one AI probability.
  const p = a.verdict === "ai_generated" ? 0.5 + a.confidence / 2 : a.verdict === "human_made" ? 0.5 - a.confidence / 2 : 0.4;
  const label = a.verdict === "ai_generated" ? "AI-generated" : a.verdict === "human_made" ? "human-made" : "unclear";
  return {
    source: "claude",
    aiProbability: Math.round(p * 100) / 100,
    summary: `Claude judges it ${label} (${Math.round(a.confidence * 100)}% confident).`,
    details: a.reasons,
  };
}

/* ------------------------------------------------------------------- combine */

export async function checkImage(bytes: Uint8Array, mime: string): Promise<ImageVerdict> {
  const detectors = detectorNames();
  const threshold = serverConfig.aiBlockThreshold;
  const signals: Signal[] = [provenance(bytes)];

  // Only pay for the external detectors when the metadata did not already settle it.
  if (signals[0].aiProbability < threshold) {
    const jobs: Promise<Signal>[] = [];
    if (sightengineConfigured()) jobs.push(sightengine(bytes, mime));
    if (claudeConfigured()) jobs.push(claude(bytes, mime));
    signals.push(...(await Promise.all(jobs)));
  }

  const aiProbability = Math.max(...signals.map((s) => s.aiProbability));
  const allowed = aiProbability < threshold;
  const verdict: Verdict = !allowed ? "ai" : aiProbability >= 0.35 ? "unclear" : "human";
  const top = signals.reduce((a, b) => (b.aiProbability > a.aiProbability ? b : a));
  const summary = !allowed
    ? `Blocked: this image looks AI-generated. ${top.summary}`
    : verdict === "unclear"
      ? `Passed with some doubt. ${top.summary}`
      : "Passed: this image looks human-made.";
  return { allowed, verdict, aiProbability, threshold, detectors, signals, summary, hash: imageHash(bytes) };
}

/* ------------------------------------------------------------ verdict tokens */

interface VerdictClaim {
  h: string;
  v: ImageVerdict;
}

export const VERDICT_TTL_MS = 15 * 60 * 1000;

export const signVerdict = (v: ImageVerdict) => signToken<VerdictClaim>({ h: v.hash, v });

/** Returns the verdict a token carries if it is genuine, fresh, and about exactly these bytes. */
export function reuseVerdict(token: string | null | undefined, bytes: Uint8Array): ImageVerdict | null {
  if (!token) return null;
  const claim = verifyToken<VerdictClaim>(token, VERDICT_TTL_MS);
  if (!claim || claim.h !== imageHash(bytes)) return null;
  return claim.v;
}
